name: instant_camera
description: A flutter plugin to quickly take pictures and videos using a built-in camera interface.
version: 0.0.2
homepage: https://github.com/deb-sahu/instant_camera

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0 
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

